import { PrismaClient, ReviewStatus, ReviewTagKind, SourceType, UserRole } from "@prisma/client";

import { hashPassword } from "../lib/auth/password";

const prisma = new PrismaClient();

type CampSeed = {
  slug: string;
  name: string;
  province: string;
  city: string;
  district: string;
  address: string;
  latitude: number;
  longitude: number;
  mapRegionKey: string;
  mapX: number;
  mapY: number;
  campType: string;
  coverImage: string;
  gallery: string[];
  priceType: string;
  priceMin: number;
  priceMax: number;
  bookingRequired: boolean;
  openingStatus: "OPEN" | "LIMITED" | "CLOSED";
  bestSeason: string;
  arrivalTips: string;
  riskTips: string;
  suitableFor: string[];
  rules: string[];
  summary: string;
  sourceType: SourceType;
  facility: {
    hasToilet: boolean;
    hasShower: boolean;
    hasPower: boolean;
    hasWater: boolean;
    allowFire: boolean;
    canOvernight: boolean;
    petFriendly: boolean;
    familyFriendly: boolean;
    carAccessible: boolean;
    signalStrength: string;
    roadCondition: string;
    parkingDistance: string;
  };
  tags: string[];
};

const tags = [
  ["newbie-friendly", "新手友好", "suitable"],
  ["family-friendly", "亲子露营", "suitable"],
  ["pet-friendly", "宠物友好", "suitable"],
  ["overnight", "可过夜", "facility"],
  ["campfire", "可明火", "facility"],
  ["lake-view", "湖边风景", "scene"],
  ["forest", "森林氧吧", "scene"],
  ["grassland", "草地宽阔", "scene"],
  ["rv-friendly", "房车可达", "facility"],
  ["photogenic", "拍照出片", "scene"],
] as const;

const reviewTags = [
  ["sunset", "落日好看", ReviewTagKind.RECOMMEND],
  ["clean-toilet", "卫生间比预期好", ReviewTagKind.RECOMMEND],
  ["stable-signal", "信号稳定", ReviewTagKind.RECOMMEND],
  ["windy-night", "夜里风大", ReviewTagKind.WARNING],
  ["crowded-holiday", "节假日偏挤", ReviewTagKind.WARNING],
  ["need-booking", "建议提前预约", ReviewTagKind.WARNING],
] as const;

const camps: CampSeed[] = [
  {
    slug: "hangzhou-lake-breeze",
    name: "湖风松坡营地",
    province: "浙江省",
    city: "杭州",
    district: "临安区",
    address: "临安区天目山脚下湖风松坡营地",
    latitude: 30.255,
    longitude: 119.71,
    mapRegionKey: "hangzhou",
    mapX: 35,
    mapY: 48,
    campType: "湖边营地",
    coverImage: "/camp/camp-1.jpg",
    gallery: ["/camp/camp-1.jpg", "/camp/camp-2.jpg", "/camp/camp-3.jpg"],
    priceType: "收费营地",
    priceMin: 198,
    priceMax: 398,
    bookingRequired: true,
    openingStatus: "OPEN",
    bestSeason: "春秋最佳",
    arrivalTips: "导航到游客中心后沿营地方向继续前行 800 米。",
    riskTips: "雨后土路稍滑，夜间温差较大。",
    suitableFor: ["新手家庭", "周末轻露营", "拍照党"],
    rules: ["22:30 后控制音量", "明火需在指定区域", "宠物需牵引"],
    summary: "湖边视野开阔，设施齐整，适合第一次带家人出发。",
    sourceType: SourceType.EDITORIAL,
    facility: {
      hasToilet: true,
      hasShower: true,
      hasPower: true,
      hasWater: true,
      allowFire: true,
      canOvernight: true,
      petFriendly: true,
      familyFriendly: true,
      carAccessible: true,
      signalStrength: "4G 稳定",
      roadCondition: "全程铺装路，最后 300 米缓坡",
      parkingDistance: "车可停到营位旁 20 米",
    },
    tags: ["newbie-friendly", "family-friendly", "pet-friendly", "overnight", "campfire", "lake-view", "photogenic"],
  },
  {
    slug: "hangzhou-pine-shadow",
    name: "松影溪谷营地",
    province: "浙江省",
    city: "杭州",
    district: "余杭区",
    address: "余杭区百丈镇松影溪谷营地",
    latitude: 30.42,
    longitude: 119.89,
    mapRegionKey: "hangzhou",
    mapX: 52,
    mapY: 36,
    campType: "森林营地",
    coverImage: "/camp/camp-4.jpg",
    gallery: ["/camp/camp-4.jpg", "/camp/camp-5.jpg", "/camp/camp-6.jpg"],
    priceType: "收费营地",
    priceMin: 128,
    priceMax: 268,
    bookingRequired: false,
    openingStatus: "OPEN",
    bestSeason: "夏秋适合",
    arrivalTips: "最后一段山路较窄，建议白天抵达。",
    riskTips: "夜晚湿气较重，蚊虫偏多。",
    suitableFor: ["朋友聚会", "轻徒步", "避暑"],
    rules: ["自备驱蚊用品", "不可私自下溪谷戏水"],
    summary: "林荫感强，安静度高，适合避暑和两天一夜周末放空。",
    sourceType: SourceType.EDITORIAL,
    facility: {
      hasToilet: true,
      hasShower: false,
      hasPower: true,
      hasWater: true,
      allowFire: false,
      canOvernight: true,
      petFriendly: false,
      familyFriendly: true,
      carAccessible: true,
      signalStrength: "移动较稳，联通偏弱",
      roadCondition: "最后 2 公里山路会车困难",
      parkingDistance: "统一停车后步行 80 米",
    },
    tags: ["newbie-friendly", "family-friendly", "overnight", "forest"],
  },
  {
    slug: "hangzhou-wild-grass",
    name: "青甸草浪营地",
    province: "浙江省",
    city: "杭州",
    district: "桐庐县",
    address: "桐庐县富春江边青甸草浪营地",
    latitude: 29.88,
    longitude: 119.68,
    mapRegionKey: "hangzhou",
    mapX: 61,
    mapY: 61,
    campType: "草地营地",
    coverImage: "/camp/camp-7.jpg",
    gallery: ["/camp/camp-7.jpg", "/camp/camp-8.jpg", "/camp/camp-9.jpg"],
    priceType: "免费点位",
    priceMin: 0,
    priceMax: 0,
    bookingRequired: false,
    openingStatus: "LIMITED",
    bestSeason: "秋季最佳",
    arrivalTips: "沿江边步道进入，需自行判断风向和搭帐位置。",
    riskTips: "免费点位，节假日容易拥挤，卫生维护波动大。",
    suitableFor: ["预算敏感用户", "天幕轻露营"],
    rules: ["请自带垃圾袋并带走", "注意防风固定"],
    summary: "免费、出片、交通方便，但更适合有一点点经验的轻露营用户。",
    sourceType: SourceType.USER_SUBMITTED,
    facility: {
      hasToilet: false,
      hasShower: false,
      hasPower: false,
      hasWater: false,
      allowFire: false,
      canOvernight: true,
      petFriendly: true,
      familyFriendly: false,
      carAccessible: false,
      signalStrength: "5G 稳定",
      roadCondition: "导航到停车场后步行 300 米",
      parkingDistance: "停车后步行约 300 米",
    },
    tags: ["overnight", "grassland", "photogenic"],
  },
  {
    slug: "hangzhou-cloud-meadow",
    name: "云岭草甸营地",
    province: "浙江省",
    city: "杭州",
    district: "淳安县",
    address: "淳安县云岭草甸营地",
    latitude: 29.61,
    longitude: 118.98,
    mapRegionKey: "hangzhou",
    mapX: 24,
    mapY: 28,
    campType: "山野营地",
    coverImage: "/camp/camp-10.jpg",
    gallery: ["/camp/camp-10.jpg", "/camp/camp-11.jpg", "/camp/camp-12.jpg"],
    priceType: "收费营地",
    priceMin: 158,
    priceMax: 258,
    bookingRequired: true,
    openingStatus: "OPEN",
    bestSeason: "夏季、初秋",
    arrivalTips: "山顶早晚温差大，建议提前联系营地确认停车区。",
    riskTips: "风大，天幕固定要求高。",
    suitableFor: ["新手双人露营", "看云海"],
    rules: ["禁止悬崖边搭营", "风力过大时禁止明火"],
    summary: "海拔略高但服务稳定，是看山景和云海的入门选择。",
    sourceType: SourceType.OFFICIAL,
    facility: {
      hasToilet: true,
      hasShower: true,
      hasPower: true,
      hasWater: true,
      allowFire: true,
      canOvernight: true,
      petFriendly: false,
      familyFriendly: true,
      carAccessible: true,
      signalStrength: "电信稳定",
      roadCondition: "盘山路较多，建议慢速",
      parkingDistance: "统一停车后步行 50 米",
    },
    tags: ["newbie-friendly", "overnight", "campfire", "grassland", "photogenic"],
  },
  {
    slug: "hangzhou-river-bend",
    name: "清江河湾营地",
    province: "浙江省",
    city: "杭州",
    district: "建德市",
    address: "建德市清江河湾营地",
    latitude: 29.53,
    longitude: 119.21,
    mapRegionKey: "hangzhou",
    mapX: 48,
    mapY: 73,
    campType: "河畔营地",
    coverImage: "/camp/camp-13.jpg",
    gallery: ["/camp/camp-13.jpg", "/camp/camp-14.jpg", "/camp/camp-15.jpg"],
    priceType: "收费营地",
    priceMin: 99,
    priceMax: 168,
    bookingRequired: false,
    openingStatus: "OPEN",
    bestSeason: "春夏",
    arrivalTips: "靠近水边区域需提前预留位置。",
    riskTips: "暴雨后水位变化快，需关注天气。",
    suitableFor: ["亲子用户", "轻装备出游"],
    rules: ["禁止下水游泳", "儿童需全程看护"],
    summary: "价格友好，配套完整，适合想低成本试一次周末露营的家庭。",
    sourceType: SourceType.EDITORIAL,
    facility: {
      hasToilet: true,
      hasShower: true,
      hasPower: false,
      hasWater: true,
      allowFire: true,
      canOvernight: true,
      petFriendly: true,
      familyFriendly: true,
      carAccessible: true,
      signalStrength: "4G 稳定",
      roadCondition: "路况轻松，导航直达",
      parkingDistance: "车位距营位 30 米",
    },
    tags: ["family-friendly", "pet-friendly", "overnight", "campfire", "lake-view"],
  },
  {
    slug: "hangzhou-bamboo-spring",
    name: "竹泉小驻营地",
    province: "浙江省",
    city: "杭州",
    district: "富阳区",
    address: "富阳区竹泉小驻营地",
    latitude: 30.05,
    longitude: 119.86,
    mapRegionKey: "hangzhou",
    mapX: 70,
    mapY: 45,
    campType: "山谷营地",
    coverImage: "/camp/camp-16.jpg",
    gallery: ["/camp/camp-16.jpg", "/camp/camp-17.jpg", "/camp/camp-18.jpg"],
    priceType: "收费营地",
    priceMin: 188,
    priceMax: 320,
    bookingRequired: true,
    openingStatus: "OPEN",
    bestSeason: "四季可去",
    arrivalTips: "入场时间建议 17:00 前。",
    riskTips: "营位数量少，周末需提前订。",
    suitableFor: ["情侣轻奢露营", "第一次过夜"],
    rules: ["严禁超员搭营", "宠物不可入内"],
    summary: "小而精的山谷营地，适合想要低决策压力的新手用户。",
    sourceType: SourceType.OFFICIAL,
    facility: {
      hasToilet: true,
      hasShower: true,
      hasPower: true,
      hasWater: true,
      allowFire: false,
      canOvernight: true,
      petFriendly: false,
      familyFriendly: true,
      carAccessible: true,
      signalStrength: "全网稳定",
      roadCondition: "全程好开",
      parkingDistance: "车可到营位旁 10 米",
    },
    tags: ["newbie-friendly", "family-friendly", "overnight", "forest"],
  },
  {
    slug: "suzhou-lake-pier",
    name: "太湖栈桥营地",
    province: "江苏省",
    city: "苏州",
    district: "吴中区",
    address: "吴中区太湖边栈桥营地",
    latitude: 31.16,
    longitude: 120.37,
    mapRegionKey: "suzhou",
    mapX: 38,
    mapY: 54,
    campType: "湖边营地",
    coverImage: "/camp/camp-2.jpg",
    gallery: ["/camp/camp-2.jpg", "/camp/camp-3.jpg", "/camp/camp-4.jpg"],
    priceType: "收费营地",
    priceMin: 168,
    priceMax: 298,
    bookingRequired: true,
    openingStatus: "OPEN",
    bestSeason: "春秋最佳",
    arrivalTips: "西门进更近，日落位靠湖边木栈道。",
    riskTips: "节假日人流大，停车等待时间长。",
    suitableFor: ["亲子", "拍照", "第一次露营"],
    rules: ["晚 10 点后不可外放音响"],
    summary: "城市周边最省心的湖边营地之一，照片出片且设施稳定。",
    sourceType: SourceType.OFFICIAL,
    facility: {
      hasToilet: true,
      hasShower: true,
      hasPower: true,
      hasWater: true,
      allowFire: false,
      canOvernight: true,
      petFriendly: true,
      familyFriendly: true,
      carAccessible: true,
      signalStrength: "5G 稳定",
      roadCondition: "导航直达",
      parkingDistance: "步行 20 米",
    },
    tags: ["newbie-friendly", "family-friendly", "pet-friendly", "overnight", "lake-view", "photogenic"],
  },
  {
    slug: "suzhou-green-island",
    name: "绿洲岛坪营地",
    province: "江苏省",
    city: "苏州",
    district: "常熟市",
    address: "常熟市虞山脚下绿洲岛坪营地",
    latitude: 31.64,
    longitude: 120.74,
    mapRegionKey: "suzhou",
    mapX: 62,
    mapY: 32,
    campType: "草地营地",
    coverImage: "/camp/camp-5.jpg",
    gallery: ["/camp/camp-5.jpg", "/camp/camp-6.jpg", "/camp/camp-7.jpg"],
    priceType: "收费营地",
    priceMin: 118,
    priceMax: 188,
    bookingRequired: false,
    openingStatus: "OPEN",
    bestSeason: "春秋",
    arrivalTips: "工作日体验更安静。",
    riskTips: "周末下午遮阴位较少。",
    suitableFor: ["三五好友", "宠物友好出游"],
    rules: ["明火仅限公区"],
    summary: "草地平整，宠物接受度高，适合不想跑太远的苏州周边用户。",
    sourceType: SourceType.EDITORIAL,
    facility: {
      hasToilet: true,
      hasShower: false,
      hasPower: true,
      hasWater: true,
      allowFire: true,
      canOvernight: true,
      petFriendly: true,
      familyFriendly: false,
      carAccessible: true,
      signalStrength: "信号稳定",
      roadCondition: "好开",
      parkingDistance: "车停旁边 30 米",
    },
    tags: ["pet-friendly", "overnight", "campfire", "grassland"],
  },
  {
    slug: "suzhou-reed-marsh",
    name: "芦汀湿地营地",
    province: "江苏省",
    city: "苏州",
    district: "昆山市",
    address: "昆山市湿地公园内芦汀营地",
    latitude: 31.38,
    longitude: 121.03,
    mapRegionKey: "suzhou",
    mapX: 79,
    mapY: 58,
    campType: "湿地营地",
    coverImage: "/camp/camp-8.jpg",
    gallery: ["/camp/camp-8.jpg", "/camp/camp-9.jpg", "/camp/camp-10.jpg"],
    priceType: "免费点位",
    priceMin: 0,
    priceMax: 0,
    bookingRequired: false,
    openingStatus: "LIMITED",
    bestSeason: "秋季",
    arrivalTips: "停车后有栈道步行 10 分钟。",
    riskTips: "蚊虫较多，洗手间距离较远。",
    suitableFor: ["拍照", "日营"],
    rules: ["不可过夜的区域需遵守公园管理"],
    summary: "更适合日间天幕和散步，不是最省心的过夜新手点。",
    sourceType: SourceType.USER_SUBMITTED,
    facility: {
      hasToilet: true,
      hasShower: false,
      hasPower: false,
      hasWater: false,
      allowFire: false,
      canOvernight: false,
      petFriendly: false,
      familyFriendly: true,
      carAccessible: false,
      signalStrength: "5G 稳定",
      roadCondition: "步行栈道",
      parkingDistance: "停车后步行 700 米",
    },
    tags: ["photogenic", "lake-view"],
  },
  {
    slug: "suzhou-fog-ridge",
    name: "雾岭星野营地",
    province: "江苏省",
    city: "苏州",
    district: "吴江区",
    address: "吴江区雾岭星野营地",
    latitude: 30.91,
    longitude: 120.63,
    mapRegionKey: "suzhou",
    mapX: 48,
    mapY: 72,
    campType: "轻奢营地",
    coverImage: "/camp/camp-11.jpg",
    gallery: ["/camp/camp-11.jpg", "/camp/camp-12.jpg", "/camp/camp-13.jpg"],
    priceType: "收费营地",
    priceMin: 228,
    priceMax: 428,
    bookingRequired: true,
    openingStatus: "OPEN",
    bestSeason: "四季可用",
    arrivalTips: "可直接导航，入住流程标准化。",
    riskTips: "旺季价格波动较大。",
    suitableFor: ["零经验新手", "两人周末放松"],
    rules: ["公共区域禁止宠物上桌", "烧烤需预约"],
    summary: "服务最标准化，适合第一次尝试露营又怕踩坑的人。",
    sourceType: SourceType.OFFICIAL,
    facility: {
      hasToilet: true,
      hasShower: true,
      hasPower: true,
      hasWater: true,
      allowFire: true,
      canOvernight: true,
      petFriendly: false,
      familyFriendly: true,
      carAccessible: true,
      signalStrength: "全网稳定",
      roadCondition: "导航直达",
      parkingDistance: "车位就在营位旁",
    },
    tags: ["newbie-friendly", "family-friendly", "overnight", "campfire", "photogenic"],
  },
  {
    slug: "suzhou-birch-creek",
    name: "白桦溪地营地",
    province: "江苏省",
    city: "苏州",
    district: "太仓市",
    address: "太仓市白桦溪地营地",
    latitude: 31.45,
    longitude: 121.09,
    mapRegionKey: "suzhou",
    mapX: 84,
    mapY: 44,
    campType: "森林营地",
    coverImage: "/camp/camp-14.jpg",
    gallery: ["/camp/camp-14.jpg", "/camp/camp-15.jpg", "/camp/camp-16.jpg"],
    priceType: "收费营地",
    priceMin: 148,
    priceMax: 260,
    bookingRequired: false,
    openingStatus: "OPEN",
    bestSeason: "春夏秋",
    arrivalTips: "工作日更适合带狗出行。",
    riskTips: "雨后草地积水明显。",
    suitableFor: ["宠物家庭", "轻松过夜"],
    rules: ["宠物需打疫苗并牵引"],
    summary: "少见的宠物友好森林营地，适合轻松过夜。",
    sourceType: SourceType.EDITORIAL,
    facility: {
      hasToilet: true,
      hasShower: true,
      hasPower: false,
      hasWater: true,
      allowFire: false,
      canOvernight: true,
      petFriendly: true,
      familyFriendly: true,
      carAccessible: true,
      signalStrength: "4G 稳定",
      roadCondition: "平整水泥路",
      parkingDistance: "步行 40 米",
    },
    tags: ["family-friendly", "pet-friendly", "overnight", "forest"],
  },
  {
    slug: "suzhou-orchard-breeze",
    name: "果园晚风营地",
    province: "江苏省",
    city: "苏州",
    district: "张家港市",
    address: "张家港市果园晚风营地",
    latitude: 31.89,
    longitude: 120.55,
    mapRegionKey: "suzhou",
    mapX: 28,
    mapY: 22,
    campType: "农园营地",
    coverImage: "/camp/camp-17.jpg",
    gallery: ["/camp/camp-17.jpg", "/camp/camp-18.jpg", "/camp/camp-1.jpg"],
    priceType: "收费营地",
    priceMin: 88,
    priceMax: 168,
    bookingRequired: false,
    openingStatus: "OPEN",
    bestSeason: "春秋果季",
    arrivalTips: "日落前抵达体验更好。",
    riskTips: "卫生间条件一般，介意者谨慎。",
    suitableFor: ["预算有限新手", "孩子采摘"],
    rules: ["公共果园区域不可踩踏采摘"],
    summary: "价格友好、活动轻松，但卫生间体验一般，适合对预算更敏感的人。",
    sourceType: SourceType.USER_SUBMITTED,
    facility: {
      hasToilet: true,
      hasShower: false,
      hasPower: false,
      hasWater: true,
      allowFire: true,
      canOvernight: true,
      petFriendly: true,
      familyFriendly: true,
      carAccessible: true,
      signalStrength: "4G 可用",
      roadCondition: "导航直达",
      parkingDistance: "车位距营位 50 米",
    },
    tags: ["family-friendly", "pet-friendly", "overnight", "campfire", "grassland"],
  },
  {
    slug: "chengdu-cloud-lake",
    name: "云湖牧歌营地",
    province: "四川省",
    city: "成都",
    district: "邛崃市",
    address: "邛崃市云湖牧歌营地",
    latitude: 30.38,
    longitude: 103.38,
    mapRegionKey: "chengdu",
    mapX: 31,
    mapY: 58,
    campType: "湖边营地",
    coverImage: "/camp/camp-3.jpg",
    gallery: ["/camp/camp-3.jpg", "/camp/camp-4.jpg", "/camp/camp-5.jpg"],
    priceType: "收费营地",
    priceMin: 168,
    priceMax: 328,
    bookingRequired: true,
    openingStatus: "OPEN",
    bestSeason: "春秋",
    arrivalTips: "节假日建议中午前到。",
    riskTips: "午后紫外线较强，遮阳要足。",
    suitableFor: ["亲子", "烧烤", "新手"],
    rules: ["烧烤区域需按营地引导使用"],
    summary: "景观和设施平衡得很好，是成都周边最稳的一类营地。",
    sourceType: SourceType.OFFICIAL,
    facility: {
      hasToilet: true,
      hasShower: true,
      hasPower: true,
      hasWater: true,
      allowFire: true,
      canOvernight: true,
      petFriendly: true,
      familyFriendly: true,
      carAccessible: true,
      signalStrength: "全网稳定",
      roadCondition: "高速转县道，整体轻松",
      parkingDistance: "车位 20 米",
    },
    tags: ["newbie-friendly", "family-friendly", "pet-friendly", "overnight", "campfire", "lake-view"],
  },
  {
    slug: "chengdu-fir-glen",
    name: "杉谷晨雾营地",
    province: "四川省",
    city: "成都",
    district: "大邑县",
    address: "大邑县山谷杉谷晨雾营地",
    latitude: 30.59,
    longitude: 103.43,
    mapRegionKey: "chengdu",
    mapX: 44,
    mapY: 41,
    campType: "森林营地",
    coverImage: "/camp/camp-6.jpg",
    gallery: ["/camp/camp-6.jpg", "/camp/camp-7.jpg", "/camp/camp-8.jpg"],
    priceType: "收费营地",
    priceMin: 138,
    priceMax: 228,
    bookingRequired: false,
    openingStatus: "OPEN",
    bestSeason: "夏季避暑",
    arrivalTips: "山里温度低，记得带外套。",
    riskTips: "雨季湿滑，低底盘车辆需谨慎。",
    suitableFor: ["两日一夜", "避暑放松"],
    rules: ["夜间禁止下溪边活动"],
    summary: "避暑感强，安静度高，但雨季路况略有门槛。",
    sourceType: SourceType.EDITORIAL,
    facility: {
      hasToilet: true,
      hasShower: true,
      hasPower: true,
      hasWater: true,
      allowFire: false,
      canOvernight: true,
      petFriendly: false,
      familyFriendly: true,
      carAccessible: true,
      signalStrength: "移动较稳",
      roadCondition: "最后 1 公里碎石路",
      parkingDistance: "步行 60 米",
    },
    tags: ["newbie-friendly", "family-friendly", "overnight", "forest"],
  },
  {
    slug: "chengdu-sunset-plain",
    name: "落霞平野营地",
    province: "四川省",
    city: "成都",
    district: "崇州市",
    address: "崇州市落霞平野营地",
    latitude: 30.67,
    longitude: 103.66,
    mapRegionKey: "chengdu",
    mapX: 58,
    mapY: 49,
    campType: "草地营地",
    coverImage: "/camp/camp-9.jpg",
    gallery: ["/camp/camp-9.jpg", "/camp/camp-10.jpg", "/camp/camp-11.jpg"],
    priceType: "免费点位",
    priceMin: 0,
    priceMax: 0,
    bookingRequired: false,
    openingStatus: "LIMITED",
    bestSeason: "秋季",
    arrivalTips: "日落前两小时到最容易占到好位置。",
    riskTips: "免费点位，假期拥挤度高。",
    suitableFor: ["拍照天幕", "低预算露营"],
    rules: ["请自行带走垃圾"],
    summary: "成都周边很火的免费天幕点，景色好但管理弱。",
    sourceType: SourceType.USER_SUBMITTED,
    facility: {
      hasToilet: false,
      hasShower: false,
      hasPower: false,
      hasWater: false,
      allowFire: false,
      canOvernight: true,
      petFriendly: true,
      familyFriendly: false,
      carAccessible: true,
      signalStrength: "信号好",
      roadCondition: "土路平整",
      parkingDistance: "车位旁边",
    },
    tags: ["overnight", "grassland", "photogenic"],
  },
  {
    slug: "chengdu-star-ridge",
    name: "星岭台地营地",
    province: "四川省",
    city: "成都",
    district: "彭州市",
    address: "彭州市星岭台地营地",
    latitude: 31.2,
    longitude: 103.9,
    mapRegionKey: "chengdu",
    mapX: 70,
    mapY: 28,
    campType: "山野营地",
    coverImage: "/camp/camp-12.jpg",
    gallery: ["/camp/camp-12.jpg", "/camp/camp-13.jpg", "/camp/camp-14.jpg"],
    priceType: "收费营地",
    priceMin: 188,
    priceMax: 288,
    bookingRequired: true,
    openingStatus: "OPEN",
    bestSeason: "夏秋",
    arrivalTips: "山顶风大，提前确认风况。",
    riskTips: "夜间温差大，不适合完全没有过夜经验的人。",
    suitableFor: ["进阶新手", "看星空"],
    rules: ["大风天气暂停天幕搭建"],
    summary: "视野极好，但风较大，更适合已经有一次过夜经验的用户。",
    sourceType: SourceType.OFFICIAL,
    facility: {
      hasToilet: true,
      hasShower: true,
      hasPower: true,
      hasWater: true,
      allowFire: true,
      canOvernight: true,
      petFriendly: false,
      familyFriendly: false,
      carAccessible: true,
      signalStrength: "电信最佳",
      roadCondition: "盘山路较多",
      parkingDistance: "步行 100 米",
    },
    tags: ["overnight", "campfire", "photogenic"],
  },
  {
    slug: "chengdu-maple-creek",
    name: "枫溪亲子营地",
    province: "四川省",
    city: "成都",
    district: "都江堰市",
    address: "都江堰市枫溪亲子营地",
    latitude: 30.99,
    longitude: 103.67,
    mapRegionKey: "chengdu",
    mapX: 47,
    mapY: 35,
    campType: "亲子营地",
    coverImage: "/camp/camp-15.jpg",
    gallery: ["/camp/camp-15.jpg", "/camp/camp-16.jpg", "/camp/camp-17.jpg"],
    priceType: "收费营地",
    priceMin: 158,
    priceMax: 268,
    bookingRequired: false,
    openingStatus: "OPEN",
    bestSeason: "春秋夏",
    arrivalTips: "营地活动较多，建议提前选靠内侧安静区。",
    riskTips: "周末儿童活动多，想要安静体验需错峰。",
    suitableFor: ["亲子初体验", "一晚轻露营"],
    rules: ["儿童活动区需穿防滑鞋"],
    summary: "设施对新手家庭很友好，适合第一次带孩子露营。",
    sourceType: SourceType.OFFICIAL,
    facility: {
      hasToilet: true,
      hasShower: true,
      hasPower: true,
      hasWater: true,
      allowFire: false,
      canOvernight: true,
      petFriendly: false,
      familyFriendly: true,
      carAccessible: true,
      signalStrength: "信号稳定",
      roadCondition: "高速后县道直达",
      parkingDistance: "30 米",
    },
    tags: ["newbie-friendly", "family-friendly", "overnight", "grassland"],
  },
  {
    slug: "chengdu-river-loop",
    name: "河湾松石营地",
    province: "四川省",
    city: "成都",
    district: "新津区",
    address: "新津区河湾松石营地",
    latitude: 30.42,
    longitude: 103.81,
    mapRegionKey: "chengdu",
    mapX: 62,
    mapY: 67,
    campType: "河边营地",
    coverImage: "/camp/camp-18.jpg",
    gallery: ["/camp/camp-18.jpg", "/camp/camp-1.jpg", "/camp/camp-2.jpg"],
    priceType: "收费营地",
    priceMin: 108,
    priceMax: 208,
    bookingRequired: false,
    openingStatus: "OPEN",
    bestSeason: "春秋",
    arrivalTips: "公共区和静音区分开，建议家庭选静音区。",
    riskTips: "河边夜晚湿气重，防潮垫要够。",
    suitableFor: ["朋友聚会", "轻社交露营"],
    rules: ["河边区域不可下水"],
    summary: "交通近、价格适中，适合成都周边短途过夜。",
    sourceType: SourceType.EDITORIAL,
    facility: {
      hasToilet: true,
      hasShower: true,
      hasPower: false,
      hasWater: true,
      allowFire: true,
      canOvernight: true,
      petFriendly: true,
      familyFriendly: true,
      carAccessible: true,
      signalStrength: "5G 稳定",
      roadCondition: "路况轻松",
      parkingDistance: "车位 25 米",
    },
    tags: ["family-friendly", "pet-friendly", "overnight", "campfire", "lake-view"],
  },
];

async function main() {
  await prisma.reviewImage.deleteMany();
  await prisma.reviewTagRelation.deleteMany();
  await prisma.review.deleteMany();
  await prisma.recentlyViewed.deleteMany();
  await prisma.favoriteListItem.deleteMany();
  await prisma.favoriteList.deleteMany();
  await prisma.correctionFeedback.deleteMany();
  await prisma.campTagRelation.deleteMany();
  await prisma.campFacility.deleteMany();
  await prisma.camp.deleteMany();
  await prisma.guide.deleteMany();
  await prisma.reviewTag.deleteMany();
  await prisma.campTag.deleteMany();
  await prisma.user.deleteMany();

  const adminPassword = await hashPassword("Admin123!");
  const userPassword = await hashPassword("User123!");

  const [admin, userA, userB] = await Promise.all([
    prisma.user.create({
      data: {
        email: "admin@luying.local",
        name: "露之营管理员",
        passwordHash: adminPassword,
        role: UserRole.ADMIN,
      },
    }),
    prisma.user.create({
      data: {
        email: "lin@luying.local",
        name: "林周末",
        passwordHash: userPassword,
      },
    }),
    prisma.user.create({
      data: {
        email: "xu@luying.local",
        name: "许小露",
        passwordHash: userPassword,
      },
    }),
  ]);

  const tagMap = new Map<string, string>();
  for (const [slug, name, category] of tags) {
    const tag = await prisma.campTag.create({
      data: { slug, name, category },
    });
    tagMap.set(slug, tag.id);
  }

  const reviewTagMap = new Map<string, string>();
  for (const [key, name, kind] of reviewTags) {
    const tag = await prisma.reviewTag.create({
      data: { name, kind },
    });
    reviewTagMap.set(key, tag.id);
  }

  const createdCamps: string[] = [];
  for (const camp of camps) {
    const created = await prisma.camp.create({
      data: {
        slug: camp.slug,
        name: camp.name,
        province: camp.province,
        city: camp.city,
        district: camp.district,
        address: camp.address,
        latitude: camp.latitude,
        longitude: camp.longitude,
        mapRegionKey: camp.mapRegionKey,
        mapX: camp.mapX,
        mapY: camp.mapY,
        campType: camp.campType,
        coverImage: camp.coverImage,
        gallery: camp.gallery,
        priceType: camp.priceType,
        priceMin: camp.priceMin,
        priceMax: camp.priceMax,
        bookingRequired: camp.bookingRequired,
        openingStatus: camp.openingStatus,
        sourceType: camp.sourceType,
        bestSeason: camp.bestSeason,
        arrivalTips: camp.arrivalTips,
        riskTips: camp.riskTips,
        suitableFor: camp.suitableFor,
        rules: camp.rules,
        summary: camp.summary,
        facility: { create: camp.facility },
        tags: {
          create: camp.tags.map((slug) => ({
            tagId: tagMap.get(slug)!,
          })),
        },
      },
    });

    createdCamps.push(created.id);
  }

  const campRows = await prisma.camp.findMany({ orderBy: { city: "asc" } });

  for (const [index, camp] of campRows.entries()) {
    const reviewBase = [
      {
        userId: userA.id,
        text: `${camp.name} 的信息基本和页面一致，卫生间维护得比我预期好，第一次带家人过去没有太大压力。傍晚风景也很舒服，适合周末一晚轻露营。`,
        tags: ["sunset", "clean-toilet"],
        status: ReviewStatus.APPROVED,
      },
      {
        userId: userB.id,
        text: `这个营地最让我满意的是到达成本低，车停好以后走几步就能到营位。唯一需要注意的是节假日确实会更热闹，如果想安静一些建议尽量错峰。`,
        tags: ["stable-signal", "crowded-holiday"],
        status: ReviewStatus.APPROVED,
      },
      {
        userId: admin.id,
        text: `从新手角度看，这里最关键的是规则比较清楚，踩坑成本低。如果是第一次过夜，建议提前确认风向、温差和预约情况，整体算比较稳。`,
        tags: ["need-booking", "windy-night"],
        status: index % 3 === 0 ? ReviewStatus.PENDING : ReviewStatus.APPROVED,
      },
    ];

    for (const [reviewIndex, item] of reviewBase.entries()) {
      await prisma.review.create({
        data: {
          campId: camp.id,
          userId: item.userId,
          overallScore: 4 + (reviewIndex % 2),
          sceneScore: 4 + (reviewIndex % 2),
          cleanScore: 4,
          quietScore: 3 + (reviewIndex % 3),
          accessScore: 4,
          newbieScore: 4,
          familyScore: 4,
          costScore: 4,
          text: item.text,
          visitDate: new Date(2026, 3 + reviewIndex, 12 + reviewIndex),
          status: item.status,
          tags: {
            create: item.tags.map((key) => ({
              tagId: reviewTagMap.get(key)!,
            })),
          },
          images:
            reviewIndex === 0
              ? {
                  create: [{ url: camp.coverImage, sortOrder: 0 }],
                }
              : undefined,
        },
      });
    }
  }

  const favorites = await Promise.all([
    prisma.favoriteList.create({
      data: {
        userId: userA.id,
        name: "周末候选营地",
      },
    }),
    prisma.favoriteList.create({
      data: {
        userId: userB.id,
        name: "亲子过夜备选",
      },
    }),
  ]);

  await prisma.favoriteListItem.createMany({
    data: [
      { listId: favorites[0].id, campId: campRows[0].id },
      { listId: favorites[0].id, campId: campRows[1].id },
      { listId: favorites[1].id, campId: campRows[6].id },
      { listId: favorites[1].id, campId: campRows[12].id },
    ],
  });

  await prisma.recentlyViewed.createMany({
    data: [
      { userId: userA.id, campId: campRows[0].id },
      { userId: userA.id, campId: campRows[4].id },
      { userId: userB.id, campId: campRows[6].id },
      { userId: userB.id, campId: campRows[14].id },
    ],
  });

  const guides = [
    ["hangzhou-first-camp", "杭州周边第一次露营怎么选营地", "新手指南", "杭州"],
    ["hangzhou-lake-weekend", "杭州周边湖边过夜营地周末精选", "城市周边", "杭州"],
    ["suzhou-family-camp", "苏州亲子露营营地避坑清单", "新手指南", "苏州"],
    ["suzhou-pet-trip", "苏州宠物友好露营地 48 小时决策指南", "专题路线", "苏州"],
    ["chengdu-newbie-overnight", "成都第一次过夜露营先看这 5 条", "新手指南", "成都"],
    ["chengdu-rainy-season", "成都雨季露营怎么避坑", "季节提醒", "成都"],
    ["summer-camp-checklist", "夏季周末露营装备清单", "季节提醒", "杭州"],
    ["family-camp-checklist", "亲子露营出发前 30 分钟检查表", "新手指南", "苏州"],
  ] as const;

  for (const [slug, title, category, cityScope] of guides) {
    await prisma.guide.create({
      data: {
        slug,
        title,
        summary: `${title}，围绕营地筛选、设施判断和新手决策展开。`,
        coverImage: "/camp/camp-4.jpg",
        category,
        cityScope,
        status: "PUBLISHED",
        publishedAt: new Date(),
        content: `## 为什么值得看\n\n这篇攻略专门服务露之营的核心用户：自驾露营新手。\n\n## 快速判断标准\n\n- 先看是否可过夜\n- 再看卫生间、淋浴和停车距离\n- 再看真实评论里的避坑标签\n\n## 出发建议\n\n优先选择评分稳定、到达成本低、规则清晰的营地。如果是第一次过夜，尽量避开免费野点和风大高海拔营地。`,
      },
    });
  }

  await prisma.correctionFeedback.create({
    data: {
      campId: campRows[2].id,
      userId: userA.id,
      fieldName: "hasToilet",
      currentValue: "无",
      suggestedValue: "停车场旁公共卫生间可用",
      reason: "我上周去的时候景区公共卫生间开放了。",
    },
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
